title: Portfolio
description: A simple SPA Portfolio template for developer/designers built with React. Use it to showcase your work, testimonials and other information to clients.
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
